In [61]:
# The code was removed by Watson Studio for sharing.

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [62]:
df.shape

(614, 13)

In [63]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [64]:
df['Credit_History'].value_counts()

1.0    475
0.0     89
Name: Credit_History, dtype: int64

In [65]:
df['Loan_Amount_Term'].value_counts()

360.0    512
180.0     44
480.0     15
300.0     13
84.0       4
240.0      4
120.0      3
36.0       2
60.0       2
12.0       1
Name: Loan_Amount_Term, dtype: int64

In [66]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [67]:
df['Credit_History'].isnull().value_counts

<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16      True
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24      True
25     False
26     False
27     False
28     False
29     False
       ...  
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600     True
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
Name: Credit_History, Length: 614, dtype: bool>

In [68]:
df.shape

(614, 13)

In [69]:
#Filling missing values
df['Gender'] = df['Gender'].fillna( df['Gender'].dropna().mode().values[0] )
df['Married'] = df['Married'].fillna( df['Married'].dropna().mode().values[0] )
df['Dependents'] = df['Dependents'].fillna( df['Dependents'].dropna().mode().values[0] )
df['Self_Employed'] = df['Self_Employed'].fillna( df['Self_Employed'].dropna().mode().values[0] )
df['LoanAmount'] = df['LoanAmount'].fillna( df['LoanAmount'].dropna().mean() )
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna( df['Loan_Amount_Term'].dropna().mode().values[0] )
df['Credit_History'] = df['Credit_History'].fillna( df['Credit_History'].dropna().mode().values[0] )
df['Dependents'] = df['Dependents'].str.rstrip('+')

In [70]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [71]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [72]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [73]:
df['Dependents'].value_counts()

0    360
1    102
2    101
3     51
Name: Dependents, dtype: int64

In [74]:
df['Property_Area'].value_counts()

Semiurban    233
Urban        202
Rural        179
Name: Property_Area, dtype: int64

In [75]:
import numpy as np
df['Married'] = df['Married'].map({'No':0, 'Yes':1}).astype(np.float)
df['Education'] = df['Education'].map({'Not Graduate':0, 'Graduate':1}).astype(np.float)
df['Self_Employed'] = df['Self_Employed'].map({'No':0, 'Yes':1}).astype(np.float)
df['Loan_Status'] = df['Loan_Status'].map({'N':0, 'Y':1}).astype(np.float)
df['Dependents'] = df['Dependents'].astype(np.float)
df['Property_Area']= df['Property_Area'].map({'Rural':0, 'Semiurban':1, 'Urban':2}).astype(np.float)

In [76]:
df.dtypes

Loan_ID               object
Gender                object
Married              float64
Dependents           float64
Education            float64
Self_Employed        float64
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area        float64
Loan_Status          float64
dtype: object

In [77]:
df.head()

Loan_ID Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002   Male      0.0         0.0        1.0            0.0   
1  LP001003   Male      1.0         1.0        1.0            0.0   
2  LP001005   Male      1.0         0.0        1.0            1.0   
3  LP001006   Male      1.0         0.0        0.0            0.0   
4  LP001008   Male      0.0         0.0        1.0            0.0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0            2.0          1.0  
1             1.0            0.0          0.0  
2             1.0            2.0          1.0  
3             1.0            2.0          1.0  
4             1.0            2.0          1.0

In [78]:
df2= df.drop('Gender', axis= 1)

In [79]:
df2.head()

Loan_ID  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0  LP001002      0.0         0.0        1.0            0.0             5849   
1  LP001003      1.0         1.0        1.0            0.0             4583   
2  LP001005      1.0         0.0        1.0            1.0             3000   
3  LP001006      1.0         0.0        0.0            0.0             2583   
4  LP001008      0.0         0.0        1.0            0.0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0            2.0          1.0  
1            0.0          0.0  
2            2.0          1.0  
3            2.0          1.0  
4            2.0          1.0

In [80]:
df3= df2.set_index('Loan_ID')

In [81]:
from sklearn import preprocessing

In [82]:
df3.columns

Index(['Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [83]:
#Converting data frames to array
X= df3[[ 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area']].values
X[0:5]

array([[  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   5.84900000e+03,   0.00000000e+00,
          1.46412162e+02,   3.60000000e+02,   1.00000000e+00,
          2.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   4.58300000e+03,   1.50800000e+03,
          1.28000000e+02,   3.60000000e+02,   1.00000000e+00,
          0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   3.00000000e+03,   0.00000000e+00,
          6.60000000e+01,   3.60000000e+02,   1.00000000e+00,
          2.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   2.58300000e+03,   2.35800000e+03,
          1.20000000e+02,   3.60000000e+02,   1.00000000e+00,
          2.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   6.00000000e+03,   0.00000000e+00,
          1.41000000e+02

In [84]:
y= df3['Loan_Status'].values

In [85]:
y[0:5]

array([ 1.,  0.,  1.,  1.,  1.])

In [86]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-1.37208932, -0.73780632,  0.52836225, -0.39260074,  0.07299082,
        -0.55448733,  0.        ,  0.2732313 ,  0.41173269,  1.22329839],
       [ 0.72881553,  0.25346957,  0.52836225, -0.39260074, -0.13441195,
        -0.03873155, -0.21927331,  0.2732313 ,  0.41173269, -1.31851281],
       [ 0.72881553, -0.73780632,  0.52836225,  2.54711697, -0.39374734,
        -0.55448733, -0.957641  ,  0.2732313 ,  0.41173269,  1.22329839],
       [ 0.72881553, -0.73780632, -1.89264089, -0.39260074, -0.46206247,
         0.2519796 , -0.31454656,  0.2732313 ,  0.41173269,  1.22329839],
       [-1.37208932, -0.73780632,  0.52836225, -0.39260074,  0.09772844,
        -0.55448733, -0.06445428,  0.2732313 ,  0.41173269,  1.22329839]])

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (429, 10) (429,)
Test set: (185, 10) (185,)


In [88]:
#Implementing K neighbors algorithm
from sklearn.neighbors import KNeighborsClassifier


In [89]:
k = 3
#Train Model and Predict  
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [90]:
yhatknn = neigh.predict(X_test)
yhatknn[0:10]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.])

In [91]:
y_test[0:10]

array([ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.])

In [93]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhatknn))

Train set Accuracy:  0.843822843823
Test set Accuracy:  0.756756756757


In [94]:
#Jaccard index for KNN
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhatknn)

0.7567567567567568

In [95]:
#F1 score for KNN
from sklearn.metrics import f1_score
f1_score(y_test, yhatknn)

0.83271375464684017

In [108]:
#Log_loss for knn
yhat_probknn = neigh.predict_proba(X_test)
yhat_probknn

array([[ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.33333333,  0.66666667],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.33333333,  0.66666667],
       [ 0.        ,  1.        ],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 1.        ,  0.        ],
       [ 0.33333333,  0.66666667],
       [ 0.        ,  1.        ],
       [ 0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667],
       [ 1.        ,  0.        ],
       [ 0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667],
       [ 0.33333333,  0.66666667],
       [ 0.        ,  1.        ],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.33333333,  0.66666667],
       [ 0.66666667,  0.33333333],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ],
       [ 0.        ,  1.        ],
       [ 0.33333333,  0.66666667],
       [ 0.66666667,

In [110]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_probknn)

4.1705339973970768

In [111]:
#Implementing Decision tree
from sklearn.tree import DecisionTreeClassifier


In [112]:
dectree = DecisionTreeClassifier(criterion='entropy', max_depth= 4)
dectree

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [120]:
#modeling
DT= dectree.fit(X_train, y_train)

In [121]:
#prediction
decpredict= dectree.predict(X_test)

In [122]:
decpredict[0:10]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.])

In [116]:
y_test[0:10]

array([ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.])

In [117]:
#accuracy of Decision tree
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, decpredict))

DecisionTrees's Accuracy:  0.789189189189


In [118]:
#Jaccard index for Decision tree
jaccard_similarity_score(y_test, decpredict)

0.78918918918918923

In [119]:
#F1 score for Decision tree
f1_score(y_test, decpredict)

0.8612099644128115

In [123]:
#LOg loss for Decison tree
decpredict_prob= DT.predict_proba(X_test)

In [124]:
log_loss(y_test, decpredict_prob)

1.3967342790832615

In [125]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [128]:
#prediction
yhat_logistic = LR.predict(X_test)
yhat_logistic

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [129]:
y_test

array([ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,
        1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [130]:
#jaccard index for logistic regression
jaccard_similarity_score(y_test, yhat_logistic)

0.80000000000000004

In [131]:
#F1 score for logistic regression
f1_score(y_test, yhat_logistic)

0.8683274021352313

In [132]:
#log loss
yhat_logistic_prob = LR.predict_proba(X_test)
log_loss(y_test,yhat_logistic_prob )

0.5466202270995667

In [133]:
#Implementing Support vector machine
from sklearn import svm

In [143]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
svmclf= clf.fit(X_train, y_train) 

In [140]:
yhat_svm= clf.predict(X_test)
yhat_svm

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [138]:
y_test

array([ 1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,
        1.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [141]:
#jaccard index of support vector machine
jaccard_similarity_score(y_test, yhat_svm)

0.80000000000000004

In [142]:
#F1 score of SVM
f1_score(y_test, yhat_svm)

0.8683274021352313

In [144]:
#log loss
yhat_svmproba= svmclf.predict_proba(X_test)

AttributeError: predict_proba is not available when  probability=False